language: python

python:
  - "3.6"

service:
  - postgresql

env:
  - APP_SETTINGS="api.server.config.TestingConfig" SECRET_KEY="this_is_the_secret_key" PGDATABASE="stackoverflow" PGUSER="postresql" PGPASSWORD="password"

before_script:
  - psql -c "CREATE DATABASE stackoverflow_test;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'password';" -U postgres

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python migrate.py
  - nosetests --exe -v
  - nosetests --exe --with-coverage --cover-package=api/server
  - coveralls

after_success:
  - "coveralls"
