language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install nose

script:
  - nosetests --exe -v
  - nosetests --exe --with-coverage --cover-package=api/endpoints
  - coveralls

after_success:
  - coveralls
